# .github/workflows/sync.yml
name: Rebase Upstream
on:
  schedule:
    - cron: '0 */6 * * *' # Run every 6 hours
  workflow_dispatch:   # run manually

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 9999 # greater than the number of commits you made
    - uses: imba-tjd/rebase-upstream-action@master
      with:
        upstream: void-linux/void-packages
        branch: master
